### ISSUE TITLE
Configure continuous deployment of the web app

### ISSUE THREAD

**Issue by rfprod** [dead-beef/webaudio-spectrum-analyser#25]
**Is your feature request related to a problem? Please describe.**
Configure deployment of the web app.

**Describe the solution you'd like**
It is offered to deploy the application to [firebase](https://firebase.google.com/).
Currenly only firebase hosting is applcable since the application does not have a backend.
When backend is present, it will be possible to deploy it to firebase functions.

**Alternatives**
[GitHub Pages](https://medium.com/front-end-weekly/ci-cd-with-github-actions-to-deploy-on-github-pages-73e225f8f131) (but it seems not to support backend if it is needed some day)

**Comment by dead-beef** [comment]
https://medium.com/front-end-weekly/ci-cd-with-github-actions-to-deploy-on-github-pages-73e225f8f131
